### PR TITLE
add missing v1.0.1 release yaml

### PR DESCRIPTION
**Pull request by displague**
Originally from https://github.com/packethost/packet-ccm/pull/56#issuecomment-655528837

This adds the missing chart for the v1.0.1 release and updates the README.md to reflect this as the latest version.

### CODE REVIEW

**Comment by displague** [comment]
When this is merged, and the next release is tagged, I will make a cluster-api-provider-packet PR to refer to this file, using the tagged URL rather than `master`.

https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/151

**Comment by deitch** [comment]
Huh, needs a rebase

**Comment by displague** [comment]
rebased.

**Comment by deitch** [comment]
Now it is happy. We will wait for CI to clear and then merge it in.

**Pull request merged**
