### PR TITLE
enable metallb

### PR DESCRIPTION
**Pull request by deitch**
This largish PR does the following:

* enables load balancers using metallb by default on Packet CCM. It can be disabled by option, as listed in the README [here](https://github.com/packethost/packet-ccm#load-balancers)
* ensures it all syncs correctly
* adds a `make fmt` command that formats the files
* updates the README doc for running locally (usually during development) with the manifests

### CODE REVIEW

**Comment by deitch** [comment]
Some important notes about the load balancer

* By default, a metallb speaker runs on all nodes, including control plane nodes. We may want to provide the user with an option to disable it. If so, future PR
* I haven't looked into using it also for a control plane load balancer, or how it would conflict with one

**Comment by gianarb** [comment]
ClusterAPi uses the spec released under `./deploy/releases` to deploy packet-ccm, will it be updated as part of the release process?

**Comment by deitch** [comment]
> ClusterAPi uses the spec released under ./deploy/releases to deploy packet-ccm, will it be updated as part of the release process?

Yes. Once this is merged in, we should cut a new release (I think v1.1.0 per semver) and then we can consume it.

**Comment by displague** [comment]
https://github.com/packethost/packet-ccm/pull/56 adds a command `make prerelease` to prepare the releases.

**Pull request merged**
